#!/bin/bash


read -p "Enter a number: " num


sum=0
temp=$num
len=${#num}

while [ $temp -gt 0 ]; do
    digit=$((temp % 10))
    sum=$((sum + digit ** len))
    temp=$((temp / 10))
done


if [ $sum -eq $num ]; then
    echo "$num is an Armstrong number."
else
    echo "$num is not an Armstrong number."
fi
___________________________________________________________________________________________________
output:
[mca@localhost ~]$ vi armstrong.sh
[mca@localhost ~]$ chmod +x armstrong.sh[mca@localhost ~]$ ./armstrong.sh
Enter a number: 153
153 is an Armstrong number.



